name: "movie_mart_pipeline"
version: "1.0.0"
config-version: 2

# Configures which 'profile' dbt uses for this project
profile: "movie_mart_pipeline"

packages-install-path: "dbt_packages_internal_v2"

# Where dbt should look for files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages_internal_v2"

# Model config
models:
    movie_mart_pipeline:
        # Staging Models -- cleaned raw data
        staging:
            +schema: staging

        # Intermediate
        intermediate:
            +schema: intermediate

        # Marts -- business logic and aggregations
        marts:
            +schema: marts

        # Analytics -- consumption layer views
        analytics:
            +materialized: view
            +schema: analytics

seeds:
    movie_mart_pipeline:
        +schema: raw
        +quote_columns: false
