#!/bin/bash
set -e 

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

-- ==============================
-- CREATE SERVICE ROLES
-- ==============================

CREATE ROLE ${ETL_DB_USER}
WITH LOGIN PASSWORD '${ETL_DB_PASSWORD}';

CREATE ROLE ${DBT_DB_USER}
WITH LOGIN PASSWORD '${DBT_DB_PASSWORD}';

CREATE ROLE ${ORCHESTRATOR_DB_USER}
WITH LOGIN PASSWORD '${ORCHESTRATOR_DB_PASSWORD}';

CREATE ROLE ${ANALYTICS_DB_USER}
WITH LOGIN PASSWORD '${ANALYTICS_DB_PASSWORD}';

-- ==============================
-- DATABASE ACCESS
-- ==============================

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${ETL_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DBT_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${ORCHESTRATOR_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${ANALYTICS_DB_USER};

EOSQL